
#Stores the list redeemable ranks.
ranks:
  vip:
    #Numerical ID of the given rank.
    id: 0
    #Name of the rank to promote the player to upon redemption.
    #(NOTE: THIS AND ANY OTHER RANK(s) MUST BE CONFIGURED IN THE LUCK PERMS PLUGIN)
    transform_to: 'vip'
  mvp:
    id: 1
    transform_to: 'mvp'